<a href="https://colab.research.google.com/github/EastHuni/Bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC%207%ED%9A%8C%20(%EC%9E%91%EC%97%85%ED%98%952).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### mart 판매 데이터를 기반으로 판매액을 예측하시오.
- 제공된 데이터 목록: mart_train.csv (훈련 데이터), mart_test.csv (평가용 데이터)
- 예측할 컬럼: total (총 판매액)
학습용 데이터(mart_train.csv)를 이용하여 총 판매액을 예측하는 모델을 만든 후, 이를 평가용 데이터(mart_test.csv)에 적용하여 얻은 예측값을 다음과 같은 형식의 CSV 파일로 생성하시오.
- 제출 파일은 다음 한 개의 컬럼을 포함해야 합니다.
- pred: 예측된 총 판매액
- 제출 파일명: 'result.csv' 제출한 모델의 성능은 RMSE(Root Mean Square Error) 평가지표에 따라 채점한다.
- 제출 CSV 파일명 및 형태: result.csv

~~~
pred
10000
20000
30000
40000
...
~~~

### 답안 제출 참고
- pd.read_csv('result.csv') 로 제출 코드 확인

# 1. 문제정의
- RMSE
- target: total
- 예측 파일명: result.csv
- 컬럼 1개(pred)

# 2. 라이브러리 및 데이터 불러오기

In [ ]:
# 데이터 불러오기
import pandas as pd
train = pd.read_csv()
test = pd.read_csv()

# 3. 탐색적 데이터 분석(EDA)

In [ ]:
# 데이터 크기 확인
train.shape, test.shape

((700, 10), (300, 9))

In [ ]:
# 샘플 확인
train.head(3)

,branch,city,customer_type,gender,product_line,total,payment_method,rating,time_of_day,day_name
0,A,Yangon,Member,Female,Health and beauty,823457.2500000000,Ewallet,9.1000000000,afternoon,Saturday
1,C,Naypyitaw,Normal,Female,Electronic accessories,120330.0000000000,Cash,9.6000000000,morning,Friday
2,A,Yangon,Normal,Male,Home and lifestyle,510788.2500000001,Credit card,7.4000000000,afternoon,Sunday

In [ ]:
test.head(3)

,branch,city,customer_type,gender,product_line,payment_method,rating,time_of_day,day_name
0,C,Naypyitaw,Normal,Female,Fashion accessories,Ewallet,9.6000000000,afternoon,Thursday
1,B,Mandalay,Normal,Male,Food and beverages,Credit card,4.3000000000,evening,Wednesday
2,B,Mandalay,Member,Female,Fashion accessories,Credit card,5.0000000000,evening,Wednesday

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   branch          700 non-null    object
 1   city            700 non-null    object
 2   customer_type   700 non-null    object
 3   gender          700 non-null    object
 4   product_line    700 non-null    object
 5   total           700 non-null    float64
 6   payment_method  700 non-null    object
 7   rating          700 non-null    float64
 8   time_of_day     700 non-null    object
 9   day_name        700 non-null    object
dtypes: float64(2), object(8)
memory usage: 54.8+ KB

In [ ]:
# 기초 통계값 확인
train.describe()

                   total         rating
count     700.0000000000 700.0000000000
mean   485078.0175000000   7.0034285714
std    364390.7265411940   1.7130784358
min     19041.7500000000   4.0000000000
25%    200119.5000000000   5.5000000000
50%    381874.5000000000   7.0000000000
75%    706127.6250000000   8.4250000000
max   1563975.0000000002  10.0000000000

In [ ]:
train.describe(include='O')

,branch,city,customer_type,gender,product_line,payment_method,time_of_day,day_name
count,700,700,700,700,700,700,700,700
unique,3,3,2,2,6,3,3,7
top,A,Yangon,Normal,Male,Sports and travel,Cash,evening,Saturday
freq,236,236,354,356,127,246,309,114

In [ ]:
test.describe(include='O')

,branch,city,customer_type,gender,product_line,payment_method,time_of_day,day_name
count,300,300,300,300,300,300,300,300
unique,3,3,2,2,6,3,3,7
top,A,Yangon,Member,Female,Electronic accessories,Ewallet,evening,Saturday
freq,104,104,155,157,58,110,123,50

In [ ]:
train.isnull().sum().sum()

0

In [ ]:
test.isnull().sum().sum()

0

In [ ]:
train['total'].value_counts()

total
283641.7500000000     2
263875.5000000000     2
415422.0000000000     2
326450.2500000000     2
130851.0000000000     2
                     ..
293391.0000000000     1
137103.7500000000     1
348232.5000000000     1
104107.5000000000     1
1535625.0000000000    1
Name: count, Length: 695, dtype: int64

In [ ]:
pd.set_option('display.float_format', '{:.10f}'.format)
train['total'].describe()

count       700.0000000000
mean     485078.0175000000
std      364390.7265411940
min       19041.7500000000
25%      200119.5000000000
50%      381874.5000000000
75%      706127.6250000000
max     1563975.0000000002
Name: total, dtype: float64

# 4. 데이터 전처리

In [ ]:
target = train.pop('total')

In [ ]:
print(train.shape, test.shape)
train = pd.get_dummies(train)
test = pd.get_dummies(test)
print(train.shape, test.shape)

(700, 9) (300, 9)
(700, 30) (300, 30)

# 5. 검증 데이터 분할

In [ ]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((560, 30), (140, 30), (560,), (140,))

# 6. 머신러닝 학습 및 평가

In [ ]:
from sklearn.metrics import mean_squared_error
def rmse(y_true, y_pred):
    return mean_squared_error(y_true, y_pred)**0.5

In [ ]:
# 선형회귀
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_tr, y_tr)
pred = lr.predict(X_val)
rmse(y_val, pred)

374016.3661648522

In [ ]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)
rmse(y_val, pred)

385935.56337360526

In [ ]:
# Xgboost
import xgboost as xgb
xg = xgb.XGBRegressor(random_state=0)
xg.fit(X_tr, y_tr)
pred = xg.predict(X_val)
rmse(y_val, pred)

442570.7070483747

In [ ]:
# LightGBM
import lightgbm as lgb
lg = lgb.LGBMRegressor(random_state=0, verbose=-1)
lg.fit(X_tr, y_tr)
pred = lg.predict(X_val)
rmse(y_val, pred)

404369.88780394377

# 7. 예측 및 결과 파일 생성

In [ ]:
pred = lr.predict(test)
result = pd.DataFrame({
    'pred':pred
})
result.to_csv("result.csv", index=False)

In [ ]:
pd.read_csv('result.csv')

                 pred
0   485484.5740277334
1   474683.4165377701
2   486669.1574532853
3   426407.8222290426
4   599942.9042138030
..                ...
295 501132.5887398274
296 554273.9221195823
297 540502.7549631427
298 550704.8821613131
299 506543.6684025061

[300 rows x 1 columns]

# 8. 성능 개선

In [ ]:
# 데이터 불러오기
import pandas as pd
train = pd.read_csv()
test = pd.read_csv()

# target 데이터
target = train.pop('total')

# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
cols = train.select_dtypes(include='O').columns

for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 선형회귀
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_tr, y_tr)
pred = lr.predict(X_val)
print(rmse(y_val, pred))

# 최종 제출 파일
pred = lr.predict(test)
result = pd.DataFrame({
    'pred':pred
})
result.to_csv("result.csv", index=False)

# 베이스라인(원핫 인코딩): 374016.3661648522
# 레이블 인코딩: 371070.1344734549

371070.1344734549