<a href="https://colab.research.google.com/github/EastHuni/Bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC%208%ED%9A%8C%20(%EC%9E%91%EC%97%85%ED%98%952).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 작업형2 - 통신사에서 고객에게 청구될 총 금액을 예측하시오.
- 제공된 데이터 목록:
    - churn_train.csv(훈련 데이터)
    - churn_test.csv(평가용 데이터)
- 예측할 컬럼: TotalCharges(총 청구액)
- 학습용 데이터(churn_train.csv)를 이용하여 총 청구액을 예측하는 모델을 만든 후 이를 평가용 데이터(churn_test.csv)
에 적용해 얻은 예측값을 다음과 같은 형식의 CSV 파일로 생성하시오.

- 제출 파일은 다음 1개의 컬럼을 포함해야 한다.
    - pred: 예측된 총 청구액
    - 제출 파일명: ‘result.csv’
- 제출한 모델의 성능은 MAE(Mean Absolute Error) 평가지표에 따라 채점한다.

## 문제정의

In [ ]:
# 문제정의
# 평가: MAE
# target: TotalCharges
# 최종파일: result.csv(컬럼 1개 pred)

## 데이터 불러오기

In [ ]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv()
test = pd.read_csv()

## 탐색적 데이터 분석(EDA)

In [ ]:
# 데이터 샘플
train.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges
0,CUST0454,Male,0,No,No,7,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Electronic check,163.45
1,CUST1145,Female,1,No,Yes,53,No,No phone service,Fiber optic,Yes,Yes,No,Yes,Yes,Yes,Month-to-month,No,Credit card,4140.89
2,CUST1138,Female,1,No,Yes,68,No,No phone service,DSL,Yes,Yes,Yes,No,No,Yes,Month-to-month,No,Mailed check,5152.36
3,CUST2645,Male,1,No,Yes,44,No,No phone service,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Credit card,5251.84
4,CUST2632,Male,0,Yes,No,7,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,No,One year,No,Electronic check,725.69

In [ ]:
# 데이터 크기
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

Train Shape: (4116, 19)
Test Shape: (1764, 18)

In [ ]:
# 데이터 정보(자료형)
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        4116 non-null   object
 1   gender            4116 non-null   object
 2   SeniorCitizen     4116 non-null   int64
 3   Partner           4116 non-null   object
 4   Dependents        4116 non-null   object
 5   tenure            4116 non-null   int64
 6   PhoneService      4116 non-null   object
 7   MultipleLines     4116 non-null   object
 8   InternetService   4116 non-null   object
 9   OnlineSecurity    4116 non-null   object
 10  OnlineBackup      4116 non-null   object
 11  DeviceProtection  4116 non-null   object
 12  TechSupport       4116 non-null   object
 13  StreamingTV       4116 non-null   object
 14  StreamingMovies   4116 non-null   object
 15  Contract          4116 non-null   object
 16  PaperlessBilling  4116 non-null   object
 17  PaymentMethod     4116 non-null   object
 18  TotalCharges      4116 non-null   float64
dtypes: float64(1), int64(2), object(16)
memory usage: 611.1+ KB
None

In [ ]:
# train 결측치 수
print(train.isnull().sum().sum())

0

In [ ]:
# test 결측치 수
print(test.isnull().sum().sum())

0

In [ ]:
# customerID unique 수
print(train['customerID'].nunique())

4116

In [ ]:
# target 기술 통계
print(train['TotalCharges'].describe())

count    4116.000000
mean     2566.580782
std      1911.356766
min        20.030000
25%      1020.922500
50%      2144.285000
75%      3765.670000
max      8589.600000
Name: TotalCharges, dtype: float64

## 데이터 전처리

In [ ]:
# 데이터 전처리
train = train.drop('customerID', axis=1)
test = test.drop(['customerID'], axis=1)
target = train.pop('TotalCharges')

In [ ]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
cols = train.select_dtypes(include='O').columns

for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

In [ ]:
train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,1,0,0,0,7,1,2,2,1,1,1,1,1,1,2,0,2
1,0,1,0,1,53,0,1,1,2,2,0,2,2,2,0,0,1
2,0,1,0,1,68,0,1,0,2,2,2,0,0,2,0,0,3
3,1,1,0,1,44,0,1,2,1,1,1,1,1,1,0,1,1
4,1,0,1,0,7,1,2,1,0,2,2,0,2,0,1,0,2

## 검증데이터 나누기

In [ ]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((3292, 17), (824, 17), (3292,), (824,))

## 모델 학습 및 평가

In [ ]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)
pred[:10]

array([3689.0103, 3767.0896, 3790.1254, 3598.7783, 3363.8465, 2222.6752,
       3870.9032, 2112.6572, 3388.1273, 3516.1994])

In [ ]:
# MAE
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_val, pred))
# 951.0960435538027

951.0960435538027

In [ ]:
# LightGBM
import lightgbm as lgb
lg = lgb.LGBMRegressor(random_state=0, verbose=-1)
lg.fit(X_tr, y_tr)
pred = lg.predict(X_val)
print(mean_absolute_error(y_val, pred))
# 952.7925407798712

952.7925407798712

In [ ]:
# 최종 제출 파일
pred = rf.predict(test)
result = pd.DataFrame({
    'pred':pred
})
result.to_csv("result.csv", index=False)

In [ ]:
# 1. pred 행의 수
print(pred.shape)

# 2. 생성한 csv 확인
print(pd.read_csv("result.csv").head())

(1764,)
        pred
0  3707.6212
1   923.7132
2  4057.4078
3   952.6143
4  1322.1638