<a href="https://colab.research.google.com/github/EastHuni/Bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC%203%ED%9A%8C%20(%EC%9E%91%EC%97%85%ED%98%952).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 작업형2
- 빅데이터 분석기사 3회 실기
- 제공된 데이터
    - train.csv
    - test.csv
- 예측할 컬럼 : TravelInsurance

### 시험에서 제공된 코드
~~~
import pandas as pd
a = pd.read_csv("train.csv")
b = pd.read_csv('test.csv')

pd.DataFrame(변수).to_csv('000000000.csv')
~~~


### 보험가입 확률을 묻는 문제
~~~
# csv 형태
# index,y_pred
# 0,0.152467
# 1,0.961511
# 2,0.151313
# 3,0.236632
...
# 494,0.121372
# 495,0.965155
# 496,0.986405

~~~

## 데이터 불러오기

In [ ]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/3_2/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/3_2/test.csv")

## EDA

In [ ]:
# target = TravelInsurance
print(train.shape, test.shape)

(1490, 10) (497, 9)

In [ ]:
train.head()

,Unnamed: 0,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad,TravelInsurance
0,888,28,Private Sector/Self Employed,Yes,1250000,6,1,No,No,0
1,1308,31,Private Sector/Self Employed,Yes,1250000,7,1,No,No,0
2,151,29,Private Sector/Self Employed,Yes,1200000,7,0,No,No,1
3,396,33,Government Sector,Yes,650000,6,1,No,No,1
4,135,28,Private Sector/Self Employed,Yes,800000,6,0,No,Yes,1

In [ ]:
print(train['TravelInsurance'].value_counts())

TravelInsurance
0    965
1    525
Name: count, dtype: int64

In [ ]:
train.info()
test.info()

print(train.nunique())
print(test.nunique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1490 non-null   int64
 1   Age                  1490 non-null   int64
 2   Employment Type      1490 non-null   object
 3   GraduateOrNot        1490 non-null   object
 4   AnnualIncome         1490 non-null   int64
 5   FamilyMembers        1490 non-null   int64
 6   ChronicDiseases      1490 non-null   int64
 7   FrequentFlyer        1490 non-null   object
 8   EverTravelledAbroad  1490 non-null   object
 9   TravelInsurance      1490 non-null   int64
dtypes: int64(6), object(4)
memory usage: 116.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           497 non-null    int64
 1   Age                  497 non-null    int64
 2   Employment Type      497 non-null    object
 3   GraduateOrNot        497 non-null    object
 4   AnnualIncome         497 non-null    int64
 5   FamilyMembers        497 non-null    int64
 6   ChronicDiseases      497 non-null    int64
 7   FrequentFlyer        497 non-null    object
 8   EverTravelledAbroad  497 non-null    object
dtypes: int64(5), object(4)
memory usage: 35.1+ KB
Unnamed: 0             1490
Age                      11
Employment Type           2
GraduateOrNot             2
AnnualIncome             30
FamilyMembers             8
ChronicDiseases           2
FrequentFlyer             2
EverTravelledAbroad       2
TravelInsurance           2
dtype: int64
Unnamed: 0             497
Age                     11
Employment Type          2
GraduateOrNot            2
AnnualIncome            27
FamilyMembers            8
ChronicDiseases          2
FrequentFlyer            2
EverTravelledAbroad      2
dtype: int64

In [ ]:

cols = ['Employment Type',  'GraduateOrNot', 'FrequentFlyer', 'EverTravelledAbroad']

In [ ]:
train.head()

,Unnamed: 0,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad,TravelInsurance
0,888,28,Private Sector/Self Employed,Yes,1250000,6,1,No,No,0
1,1308,31,Private Sector/Self Employed,Yes,1250000,7,1,No,No,0
2,151,29,Private Sector/Self Employed,Yes,1200000,7,0,No,No,1
3,396,33,Government Sector,Yes,650000,6,1,No,No,1
4,135,28,Private Sector/Self Employed,Yes,800000,6,0,No,Yes,1

## 데이터 전처리 및 피처엔지니어링

In [ ]:
target = train.pop('TravelInsurance')

In [ ]:
from sklearn.preprocessing import LabelEncoder
cols = ['Employment Type',  'GraduateOrNot', 'FrequentFlyer', 'EverTravelledAbroad']
le = LabelEncoder()
for col in cols:
  train[col] = le.fit_transform(train[col])
  test[col] = le.transform(test[col])

In [ ]:
print(train.shape, test.shape)

(1490, 9) (497, 9)

## 검증데이터 분리

In [ ]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val =train_test_split(train, target, test_size = 0.1 , random_state = 2022)
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

(1341, 9) (149, 9) (1341,) (149,)

## 모델 학습 및 예측

In [ ]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
model = RandomForestClassifier()
model.fit(X_tr, y_tr)
pred = model.predict_proba(X_val)

In [ ]:
# 평가
roc_auc_score(y_val, pred[:,1])

np.float64(0.6818181818181818)

## 예측

In [ ]:
# test 예측
pred = model.predict_proba(test)

In [ ]:
# csv 파일1 생성 (예시와 다른 형태)
pd.DataFrame({'index':test.index,'y_pred':pred[:,1]}).to_csv('result.csv', index = False)

In [ ]:
# csv 파일2 생성

In [ ]:
# csv 파일1 확인
df = pd.read_csv("result.csv")
df

     index  y_pred
0        0    0.26
1        1    0.14
2        2    0.06
3        3    0.99
4        4    0.17
..     ...     ...
492    492    0.10
493    493    1.00
494    494    0.11
495    495    0.95
496    496    1.00

[497 rows x 2 columns]

In [ ]:
# csv 파일2 확인

## 체점
- 수험자는 알 수 없는 부분임

In [ ]:
 y_test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/3_2/y_test.csv")
 roc_auc_score(y_test, pred[:,1])

np.float64(0.7720980595980597)

In [ ]:
# 당신의 score는?: 0.7875693000693